### ISSUE TITLE
How to control generic AC

### ISSUE THREAD

**Issue by x10iman** [shirriff/Arduino-IRremote#81]
I managed to record and send the IR signal of my General AC unit and another Chinese brand unit by increasing the RAWBUF to 250 and the USECPERTICK to 100.

**Comment by z3t0** [comment]
@x10iman not sure if this is an issue or not, maybe it should be added to a wiki for this library?

**Comment by x10iman** [comment]
It would be greate. But does this increase affect the code?

**Comment by z3t0** [comment]
@x10iman not sure, where did you change the RAWBUF and USECPERTICK values?

**Comment by x10iman** [comment]
I will let you know once I get back home in few hours.

**Comment by x10iman** [comment]
Sorry my late reply,
In those lines in IRremote.h

#define USECPERTICK 50  // microseconds per clock interrupt tick
#define RAWBUF 100 // Length of raw duration buffer

i have changed them to:

#define USECPERTICK 100  // microseconds per clock interrupt tick
#define RAWBUF 250 // Length of raw duration buffer

**Comment by z3t0** [comment]
It definitely affects the code as those 2 variables are used by the library to actually operate the infrared signals, I don't know much more than that at this moment. It would be best to add this to the wiki instead of as a commit, at least until I figure out how to implement it (or someone else does). 

I will close this issue but label it to be added to the wiki, so that this isn't ignored.
